export enum MonthCalcFieldNames {
  armenSalary = "Armen's salary",
  nastiaSalary = "Nastia's salary",
  statisticAmountSpent = "Amount spent during this period",
  daysOfAnalyticsFirst = "The first day of analysis",
  daysOfAnalyticsLast = "The last day of analysis",
  investmentPercent = "Interest for investment",
  isHelpingArmy = "Helping the Army",
  isMonthlyAidToTheArmy = "Monthly aid to the Army",
  investmentPartForArmy = "A part for the Army",
  investmentMilitaryBonds = "Military bonds",
  investmentComBackAlive = "Come Back Alive",
  futureExpenses = "Future expenses",
  currentBalance = "Current balance",
}
